apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: front
  labels:
    app: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: idanbrody/shop-app:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: 'mysql.backend'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: Kuku1234!

