apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: backend
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: idanbrody/shop-mysql:1.0.2
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Kuku1234!
            - name: MYSQL_DATABASE
              value: shoe_store
          imagePullPolicy: IfNotPresent

